apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposurelog
  labels:
    app: exposurelog
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exposurelog
  template:
    metadata:
      labels:
        name: exposurelog
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/exposurelog"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: exposurelog
