apiVersion: v1
kind: Service
metadata:
  name: exposurelog
  labels:
    app: exposurelog
spec:
  ports:
    - name: exposurelog-http
      protocol: TCP
      port: 8080
      targetPort: app
  selector:
    name: exposurelog
